### ISSUE TITLE
Double withdraws for single withdraw user action

### ISSUE THREAD

**Issue by KeepBitcoinFree-org** [sschueller/slp-bot#2]
Seeing double withdraws happening for users upon one "withdraw" command. It's not occurring every time but it seems to happen every few withdraws. I've disabled withdraws and I'm trying to troubleshoot & debug the code to see where or how it could be happening. Looking in index.js & slp.js files in the withdraw functions. 

Thanks!
BitcoinCash@KeepBitcoinFree.org

**Comment by sschueller** [comment]
Interesting, 

Is it possible the bot is multiple times? There is no check at the moment to verify it isn't. I may need to add a block or something to prevent the withdrawal being called more than once before the first call is completed.

What is really need is a complete transaction log with all deposits, withdraws and tips which I would like to add at some point.

Please let me know what you find. 

Thanks

**Comment by KeepBitcoinFree-org** [comment]
Thanks for the help! The tester finally provided more details about reproducing the issue. As it turns out, this is only happening when a user spams the withdraw command (immediate copy & paste after the first one). Doing so will trigger a second withdraw, and generates another transactionId before the first one is completed & balance is updated.

I will see if I can also work in a check/block during the withdraw that would return an error for that same user. A complete transaction log would also be great to have. For now, it at least documents all deposit & withdraw actions & userIds within the console logs for debugging. If I get something working, I will let you know. I'm still new to Node.js but glad to help contribute however I can.

Thanks!
BitcoinCash@KeepBitcoinFree.org

**Comment by KeepBitcoinFree-org** [comment]
I was able to resolve the issue by creating an array to store the userId during a withdraw. The UserId is pushed to the array at the beginning of the withdraw & then spliced out at any error or at the end of the withdraw. If the userId already exists within the array when a withdraw command is given, it will recognize this and return an error that the withdraw is already in progress. This is all done within index.js. Everything is working as expected right now. I'll open a pull request for 'withdraw blocker functionality' and you can take a look at it.

Thanks,
BitcoinCash@KeepBitcoinFree.org

**Comment by sschueller** [comment]
Thank you, it is now merged into the master and release 0.1.0
