### ISSUE TITLE
Deposit not being picked up by socket

### ISSUE THREAD

**Issue by KeepBitcoinFree-org** [sschueller/slp-bot#5]
Starting today, I'm seeing an issue where a deposit is not recognized and credited to a user's account (while the bot is running). The deposit command properly generates an SLP address for the user but upon sending tokens, nothing happens. Deposits had been working with no issues for the past week during testing but now it's not crediting to the account anymore. I'm thinking it could possibly be connectivity with the SLP servers. I'm doing some more debugging on it and trying to see how/where that balance update is kicked off. Looks like you have a socket open to check all new SLP Tx and then trigger an update based on the address. I'll also see if I can set up a function to add any missed deposits. 

Thanks!
BitcoinCash@KeepBitcoinFree.org

**Comment by sschueller** [comment]
I think it is relates to this: https://github.com/Bitcoin-com/slp-sdk/issues/88

**Comment by sschueller** [comment]
I have added a full transaction log and a separate SLPDB query that is triggered every 60 seconds. If the websocket fails the transactions will be picked up latest when they are confirmed. If you are using the nginx systemd script make sure you add the `WorkingDirectory` to the service configuration as otherwise the DB migrations will fail.

**Comment by KeepBitcoinFree-org** [comment]
Thanks for your work on this! I had almost finished creating a temporary solution. It appears that an SLPDB query (not through the websocket itself) will pick up unconf SLP txs more often than the websocket from my testing. Oddly, it's not working all the time though. It looks to be related to an overload on the SLPDB servers.

Your solution is working well, although it looks like you're actually checking each block for new transactions one at a time? That might be a bit more than necessary.

Here's what I was working on -
For each user (that calls deposit). After giving the address, query SLPDB for any outputs matching the depositAddress and the correct tokenID:
    const queryUnconf = {
    "v": 3,
    "q": {
      "db": ["u"],
      "find": {"out.e.a" : depositAddress,
        "slp.detail.tokenIdHex" : config.token_address
              }
         }
    }

every 15-30 seconds or so until a new deposit is detected for that address & token (or until it runs x times). And I would also run a query to detect all confirmed transactions for that address as well Then check all tx found against the tx ids within the DB to see if there are any new ones and deposit to user & record in DB.

**Comment by sschueller** [comment]
Yes that would make more sense. I will see if I can adjust the query. There is a way to do a IN query like so:

```
{ "out.e.a": { $in: ["depositAddress1", "depositAddres2"] } },
```

**Comment by KeepBitcoinFree-org** [comment]
Hmmm. Inputting that query structure into the SLPDB explorer gives a "bad string" error so it doesn't seem like it. The explorer is a great way to test queries though -
https://slpdb.bitcoin.com/explorer
